{
 "title": "pretty",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Senest",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n addr, \n temperature as temp,\n time\n \n FROM \n temperatures \n WHERE \n \t$__timeFilter(\"time\")\nGROUP BY addr, time, temperature\nORDER BY time\n "
    }
   ]
  },
  {
   "title": "Seneste måling",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n time\n \n FROM \n temperatures \nORDER BY time DESC\nLIMIT 1\n "
    }
   ]
  },
  {
   "title": "delta",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expression": "$A-$B", "type": "math" }
   ]
  },
  {
   "title": "Over tid",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT \n addr, \n temperature as temp,\n time\n \n FROM \n temperatures \n WHERE \n \t$__timeFilter(\"time\")\nGROUP BY addr, time, temperature\nORDER BY time\n "
    }
   ]
  }
 ]
}